name: pre-release

on:
  issue_comment:
    types: [created]

jobs:
  pre-release:
    if: contains(github.event.comment.body, 'prerelease')
    runs-on: ubuntu-latest

    steps:
      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "eyes",
            });
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Echo Running Message
        run: echo "Pipeline is running"
      - name: Display README
        run: cat README.md
