name: pre-release

on:
  issue_comment:
    types: [created]

jobs:
  pre-release:
    if: contains(github.event.comment.body, 'prerelease')
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Branch
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const { owner, repo } = context.repo;
            const pr = await github.pulls.get({ owner, repo, pull_number: issue_number });
            return pr.data.head.ref;
          result-encoding: string

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.result }}
          fetch-depth: 1

      - name: Echo Running Message
        run: echo "Pipeline is running"

      - name: Display README
        run: cat README.md
