name: pre-release

on:
  issue_comment:
    types: [created]

jobs:
  pre-release:
    if: contains(github.event.comment.body, 'prerelease')
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Branch
        id: pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const issue_number = context.payload.issue.number;
            const { owner, repo } = context.repo;

            // Fetch issue details
            const issue = await github.issues.get({ owner, repo, issue_number });

            // Check if it's a PR
            if (!issue.data.pull_request) {
              throw new Error("This issue is not linked to a PR.");
            }

            // Fetch PR details
            const pr = await github.pulls.get({ owner, repo, pull_number: issue_number });
            return pr.data.head.ref;

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.result }}
          fetch-depth: 1

      - name: Echo Running Message
        run: echo "Pipeline is running"

      - name: Display README
        run: cat README.md

