name: pre-release

on:
  issue_comment:
    types: [created]

jobs:
  pre-release:
    if: contains(github.event.comment.body, 'prerelease')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          fetch-depth: 1
      - name: Echo Running Message
        run: echo "Pipeline is running"
      - name: Display README
        run: cat README.md
